### PR TITLE
Change Subsonic API version for server support

### LINKED ISSUE #144: Incompatible REST protocol version - MadSonic 6.2.9084
**Describe the bug**
Trying to connect to my Madsonic server gives the error: Incompatible REST protocol version. Server must upgrade.

**To Reproduce**
Launch Application
Attempt to connect to MadSonic

**Expected behavior**
Connect to Madsonic

**Desktop :**
 - OS: Windows
 - Version 10

**Server:**
 - OS: Ubuntu
 - Version 20:04LTS

**Additional context**
Madsonic info:
Version	MADSONIC 6.2.9084.8df1ddd.20190425.0305
REST	MADSONIC REST API v2.5.0, SUBSONIC REST API v1.14.0

I am able to connect just fine with several iOS apps to the server with full functionality.

### PR DESCRIPTION
**Pull request by jeffvli**
Closes #144 

- 1.15.0 -> 1.13.0

### CODE REVIEW

File: src/components/settings/Login.tsx [hunk 1]
```diff
@@ -37,10 +37,10 @@ const Login = () => {
     try {
       const testConnection = legacyAuth
         ? await axios.get(
-            `${cleanServerName}/rest/ping?v=1.15.0&c=sonixd&f=json&u=${userName}&p=${password}`
+            `${cleanServerName}/rest/ping?v=1.13.0&c=sonixd&f=json&u=${userName}&p=${password}`
```
Comment (TLCFEM) [inline src/components/settings/Login.tsx:40]: Should the API be /rest/ping.view?v=

Comment (TLCFEM) [reply src/components/settings/Login.tsx:40]: /rest/ping? does not work.

**Review by TLCFEM — COMMENTED** [review]
subsonic is broken for the moment.
